spring:
  profiles:
    active: local
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
server:
  port: ${PORT:5001}
logging:
  file: 
    name: /var/log/sumire/sumire.bot.log
  charset:
    file: UTF-8
    console: UTF-8