spring:
  profiles:
    active: local
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
logging:
  file: /var/log/sumire/sumire.batch.log
