spring:
  profiles:
    active: local
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
server:
  port: ${PORT:5002}
logging:
  file: /var/log/sumire/sumire.web.log

